unroll_steps = 2

[trainer]
    exp_name = 'ffhq256-hourglass-3103-4'
    batch_size = 32
    nb_batches = [256, 32]
    learning_rate = 3e-5
    metric_names = ['accuracy']
    checkpoint_frequency = 5000
    lr_scheduler_name = 'constant'

[data]
    root = 'data/ffhq256-latents'
    vocab_size = 1024
    sequence_length = 256
    split_sizes = [120000, 10000, 10000]

[vqgan]
    config = 'config/vqgan/ffhq256.yaml'
    checkpoint = 'vqgan-ckpt/ffhq256.ckpt'
    latent_shape = [16, 16]

[sampling]
    steps = 100
    nb_samples = 4
    temperature = 0.8
    end_temperature = 0.8
    sample_proportion = 0.5
    end_sample_proportion = 0.5

[net]
    type = 'hourglass'
    dim = 1024
    nb_heads = 8
    shorten_factor = 4
    depth = [3, 10, 3]
    use_rotary = true
    conditional = false
