unroll_steps = 2

[trainer]
    exp_name = 'ffhq256-hourglass'
    batch_size = 24
    nb_batches = [256, 32]
    learning_rate = 3e-5
    metric_names = ['accuracy']
    checkpoint_frequency = 5000
    lr_scheduler_name = 'constant'

[data]
    root = 'latent-data-flipped/'
    vocab_size = 1024
    sequence_length = 256
    split_sizes = [120000, 10000, 10000]

[vqgan]
    config = 'ffhq.yaml'
    checkpoint = 'ffhq.ckpt'
    latent_shape = [16, 16]

[sampling]
    steps = 1000
    nb_samples = 4
    temperature = 0.8
    sample_proportion = 0.3

[net]
    type = 'hourglass'
    dim = 1024
    nb_heads = 8
    shorten_factor = 4
    depth = [3, 6, 4]
    use_rotary = true
