unroll_steps = 2

[trainer]
    exp_name = 'ffhq256-hourglass'
    batch_size = 8
    nb_batches = [128, 16]
    learning_rate = 3e-5
    metric_names = ['accuracy']
    checkpoint_frequency = 5000
    lr_scheduler_name = 'constant'
    max_steps = 400000

[data]
    root = 'data/ffhq256-latents'
    vocab_size = 1024
    sequence_length = 256
    split_sizes = [120000, 10000, 10000]

[vqgan]
    config = 'config/vqgan/ffhq256.yaml'
    checkpoint = 'vqgan-ckpt/ffhq256.ckpt'
    latent_shape = [16, 16]

[sampling]
    steps = 1000
    nb_samples = 4
    temperature = 0.8
    sample_proportion = 0.3

[net]
    type = 'hourglass'
    dim = 1024
    nb_heads = 8
    shorten_factor = 4
    depth = [3, 6, 3]
    use_rotary = true
