model:
  base_learning_rate: 5.0e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 1024
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: [64]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 15000
        disc_weight: 0.5
        disc_num_layers: 3
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: data/ffhq1024-train
        size: 1024
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: data/ffhq1024-validation
        size: 1024

